DROP TABLE IF EXIST ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY,MATRICULA VARCHAR(50) NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);
INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO) VALUES ( 456,'Franco', 'Guaman') (123, 'Gissel','Ferrin');

